version: '3.9'
services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=minhdeptrai123
      - POSTGRES_DB=banking
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:minhdeptrai123@postgres:5432/banking?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
